#ifndef CONSTANTS_H
#define CONSTANTS_H

#define ENEMY_STATE_PATH        1
#define ENEMY_STATE_DEAD        2
#define ENEMY_STATE_PUNCHED     3
#define ENEMY_PROJECTILE_DELAY  3000.0f
#define ENEMY_DEFAULT_VELOCITY -0.1
#define ENEMY_ROCKET_PROJECTILE_VELOCITY_X -0.3f
#define ENEMY_ROCKET_PROJECTILE_VELOCITY_Y 0.0f
#define ENEMY_SPAWN_DELAY 1000.0f

#define ENGINE_MAX_SFX  10
#define SFX_SHOOT       0
#define SFX_PUNCH_1     1
#define SFX_PUNCH_2     2
#define SFX_BOING       3
#define SFX_EXPLOSION_1 4
#define SFX_EXPLOSION_2 5
#define SFX_COIN_GET    6
#define SFX_HEALTH_GET  7


#define ENGINE_ERROR           -1
#define ENGINE_OK               0
#define ENGINE_QUIT             1
#define ENGINE_MAX_BACKGROUNDS  5 
#define ENGINE_MAX_PROJECTILES  500
#define ENGINE_MAX_VFX          100
#define ENGINE_MAX_COLLECTABLES 100
#define ENGINE_MAX_TFX          50
#define ENGINE_NUM_HUD_ELEMENTS 3 
#define ENGINE_MAX_ENEMIES      50


#define PROJECTILE_PUNCH_VELOCITY_X    1.0f
#define PROJECTILE_PUNCH_VELOCITY_Y    0.0f
#define PROJECTILE_DEFAULT_VELOCITY_X  3.0f
#define PROJECTILE_DEFAULT_VELOCITY_Y  0.0f
#define PROJECTILE_DEFAULT_DELAY       25.0f
#define PROJECTILE_DEFAULT_PUNCH_DELAY 1000.0f
#define PROJECTILE_TYPE_PUNCH          1
#define PROJECTILE_TYPE_DEFAULT        2 
#define PROJECTILE_TYPE_BULLET         3 
#define PROJECTILE_TYPE_ENEMY_ROCKET   4
#define PROJECTILE_PUNCH_COST          5 

#define PLAYER_DEFAULT_SPEED 0.3f
#define PLAYER_STATE_ALIVE   1
#define PLAYER_STATE_DEAD    2 

#define COLLECTABLE_TYPE_COIN   1
#define COLLECTABLE_TYPE_HEALTH 2 

#define VFX_TYPE_ENEMY_EXPLOSION 1
#define VFX_TYPE_PLAYER_EXPLOSION 2

#define DEFAULT_FONT_SIZE 28

#endif // CONSTANTS_H
